# This is a basic workflow to help you get started with Actions

name: Deploy Python code to Lambda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: cclauss/GitHub-Action-for-pytest@0.5.0
    - name: GitHub Action for pytest
      run: |
        pytest test_handler.py

  deploy:
    needs: pytest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy Python Code to AWS Lambda
      uses: ovsen/action-deploy-aws-lambda@1.2
      with:
        lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        lambda_region: 'na-east-1'
