# This is a basic workflow to help you get started with Actions

name: Deploy Python code to Lambda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0
      with:
        args: test_handler.py
    - name: Deploy Python 3.8 code to Lambda
      uses: gwtechnologies/action-lambda-python-zip@1.6
      with:
        lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        lambda_region: 'na-east-1'
