# This is a basic workflow to help you get started with Actions

name: Deploy Python code to Lambda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: CF-Auto
          template: template.yaml
  zip:
    needs: cloudformation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Pytest
        uses: fylein/python-pytest-github-action@v2
        with:
          args: pip3 install -r requirements.txt && pytest test_handler.py
      - name: zip file
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          exclusions: '*.git*  *.md *.txt'
      - name: deploy to lambda
        uses: stcalica/update-lambda@master
        with:
          package: release.zip
          function-name: addvisits
          AWS_REGION: us-east-1
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
