# This is a basic workflow to help you get started with Actions

name: Deploy Python code to Lambda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: zip file
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          exclusions: '*.git*  *.md *.txt'
      - name: deploy to lambda
        uses: stcalica/update-lambda@master
        with:
          package: release.zip
          function-name: addvisits
          AWS_REGION: us-east-1
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
